version: "3.8"

services:
  app:
    build: ./
    restart: unless-stopped
    env_file: ./.env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.app-secure.entrypoints=websecure"
      - "traefik.http.routers.app-secure.rule=Host(`ban4bot.teleguid.com`)"
